# The URL the site will be built for
base_url = "https://jonahnestrick.com"

# The site title and description; used in feeds by default.
title = "Jonah Nestrick"
description = "My personal blog"

# The default language; used in feeds.
default_language = "en"

compile_sass = false

author = "Jonah Nestrick <jonah.nestrick@gmail.com>"


generate_sitemap = true
generate_robots_txt = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "zolanight"

generate_feeds = true
feed_limit = 10
feed_filenames = ["atom.xml"]

taxonomies = [{ name = "tags" }]

[extra.zolanight]
theme = "tokyonight" # Choose from "tokyonight", "tokyostorm", "tokyomoon", "tokyoday"

[link_checker]
skip_prefixes = [
    "https://developer.arm.com/",
    "https://www.linkedin.com/",
]

[markdown]
insert_anchor_links = "none"

[markdown.highlighting]
error_on_missing_language = true
theme = "catppuccin-mocha"

[extra]
# Put all your custom variables here
